project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/arujthecurator
      - icon: linkedin
        href: https://www.linkedin.com/in/aruj-nayak-873187191/
format:
  html:
    theme: cosmo
    css: styles.css



